#!/bin/sh
BACKUP=false
if [ "$1" = "-b" ] ; then
	BACKUP=true
	shift
fi

formatiere() {
cp $1 $1\~
cat $1\~ | indent -kr -i8 -cli8 -psl -lp | \
sed -e 's/^        /	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/^\(	\+\)        /\1	/g' \
    -e 's/[ 	]\+$//g' > $1
if ! $BACKUP ; then
	rm $1\~
fi
}

for f in $* ; do
	formatiere $f
done

