#!/bin/sh

KERNELDIR=/usr/src/linux
DOCP=docp

docpd() {
  if ! cmp -s $1 $2 ; then
    echo Copying $1 ...
    cp $1 $2
#  else
#    echo $2 is up to date, NOT converted
  fi
}

docp() {
  if [ $1 -nt $2 -o ! -f $2 ] ; then
    echo Copying $1 ...
    cp $1 $2
#  else
#    echo $2 is up to date, NOT converted
  fi
}

#
# Check, if argument is a linux kernel dir
#
checkkernel() {
	if [ -f $1/Makefile ] ; then
		if [ "`grep do-it-all $1/Makefile | grep vmlinux`" != "" ] ; then
			return 0
		fi
	fi
	echo "The given argument does not look like a kernel dir"
	exit 1
}

while getopts :dk: a ; do
	case $a in
		\?)	case $OPTARG in
				k)	echo "-k requires Kernel directory parameter"
					;;
				*)  echo "Unknown option: -$OPTARG"
					;;
			esac
			exit 1
			;;
		k)	checkkernel $OPTARG
			KERNELDIR=$OPTARG
			;;
		d)	DOCP=docpd
	esac
done
shift `expr $OPTIND - 1`

if [ $# != 0 ]; then
  for i in $* ; do
    $DOCP $i $KERNELDIR/$i
  done
else
  for i in drivers/isdn/isdn_*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/icn/icn.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/pcbit/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/teles/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/hisax/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/sc/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/avmb1/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in include/linux/*.h ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in Documentation/isdn/CREDITS Documentation/isdn/README* \
           Documentation/isdn/*.FAQ Documentation/isdn/INTERFACE \
           Documentation/isdn/00-INDEX ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/Config.in ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/Makefile drivers/isdn/icn/Makefile \
           drivers/isdn/teles/Makefile drivers/isdn/hisax/Makefile \
           drivers/isdn/pcbit/Makefile drivers/isdn/sc/Makefile \
           drivers/isdn/avmb1/Makefile; do
    $DOCP $i.kernel $KERNELDIR/$i
  done
fi
