#!/bin/sh

KERNELDIR=/usr/src/linux

docpd() {
  if ! cmp -s $1 $2 ; then
    echo Copying $1 ...
    cp $1 $2
#  else
#    echo $2 is up to date, NOT converted
  fi
}

docp() {
  if [ $1 -nt $2 ] ; then
    echo Copying $1 ...
    cp $1 $2
#  else
#    echo $2 is up to date, NOT converted
  fi
}

if [ "$1" = "-d" ] ; then
  DOCP=docpd
  shift
else
  DOCP=docp
fi
if [ $# != 0 ]; then
  for i in $* ; do
    $DOCP $i $KERNELDIR/$i
  done
else
  for i in drivers/isdn/isdn_*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/icn/icn.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/pcbit/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in drivers/isdn/teles/*.[ch] ; do
    $DOCP $i $KERNELDIR/$i
  done
  for i in include/linux/isdn*.h ; do
    $DOCP $i $KERNELDIR/$i
  done
fi

