#!/bin/sh

KERNELDIR=/usr/src/linux

if [ $# != 0 ]; then
  for i in $* ; do
    diff -u $i $KERNELDIR/$i
  done
else
  for i in drivers/isdn/isdn_*.[ch] ; do
    diff -u $i $KERNELDIR/$i
  done
  for i in drivers/isdn/icn/icn.[ch] ; do
    diff -u $i $KERNELDIR/$i
  done
  for i in drivers/isdn/teles/*.[ch] ; do
    diff -u $i $KERNELDIR/$i
  done
  for i in drivers/isdn/pcbit/*.[ch] ; do
    diff -u $i $KERNELDIR/$i
  done
  for i in include/linux/isdn*.h ; do
    diff -u $i $KERNELDIR/$i
  done
fi

